=== dnajdrowski/PROJEKTXML/ligazuzlowa.dtd
<!-- stadion and stadions -->
        <!ATTLIST stadion id ID #REQUIRED>
        <!ATTLIST length unit CDATA #FIXED "m">
        <!ENTITY % stadion_ "name, capacity, lighting, length, record">
        <!ELEMENT stadion (%stadion_;)>
        <!ELEMENT stadions (stadion+)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT capacity (#PCDATA)>
        <!ELEMENT lighting (#PCDATA)>
        <!ELEMENT length (#PCDATA)>
        <!ELEMENT record (#PCDATA)>

        <!-- team and teams -->
        <!ATTLIST team id ID #REQUIRED>
        <!ATTLIST city id ID #REQUIRED>
        <!ATTLIST teamstadion refid IDREF #REQUIRED>
        <!ENTITY % address_ "street, housenumber, postcode, city">
        <!ENTITY % team_ "name, address, email, phonenumber, establishmentyear, president, coach, teamstadion, win, draw, lost, points, bilans">
        <!ELEMENT address (%address_;)>
        <!ELEMENT team (%team_;)>
        <!ELEMENT teams (team+)>
        <!ELEMENT teamstadion EMPTY>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT housenumber (#PCDATA)>
        <!ELEMENT postcode (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT phonenumber (#PCDATA)>
        <!ELEMENT establishmentyear (#PCDATA)>
        <!ELEMENT president (#PCDATA)>
        <!ELEMENT coach (#PCDATA)>
        <!ELEMENT win (#PCDATA)>
        <!ELEMENT draw (#PCDATA)>
        <!ELEMENT lost (#PCDATA)>
        <!ELEMENT points (#PCDATA)>
        <!ELEMENT bilans (#PCDATA)>

        <!-- rider and riders -->
        <!ATTLIST nationality code CDATA #REQUIRED>
        <!ATTLIST riderteam refid IDREF #REQUIRED>
        <!ENTITY % rider_ "firstname, lastname, birthdate, nationality, federation, riderteam">
        <!ELEMENT rider (%rider_;)>
        <!ELEMENT riders (rider+)>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT lastname (#PCDATA)>
        <!ELEMENT birthdate (#PCDATA)>
        <!ELEMENT nationality (#PCDATA)>
        <!ELEMENT federation (#PCDATA)>
        <!ELEMENT riderteam (#PCDATA)>

        <!-- speedwayleague -->
        <!ELEMENT speedwayleague (name, stadions, teams, riders)>

=== dnajdrowski/PROJEKTXML/ligazuzlowa.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE speedwayleague SYSTEM "ligazuzlowa.dtd">

<speedwayleague>
    <name>Ekstaliga</name>

    <stadions>
        <stadion id="SGPAC">
            <name>SGP Arena Częstochowa</name>
            <capacity>16850</capacity>
            <lighting>1800 lx</lighting>
            <length unit="m">359</length>
            <record>62.20</record>
        </stadion>

        <stadion id="SEJ">
            <name>Stadion im. Edwarda Jancarza</name>
            <capacity>17024</capacity>
            <lighting>1800 lx</lighting>
            <length unit="m">329</length>
            <record>58.00</record>
        </stadion>

        <stadion id="SGKMG">
            <name>Stadion GKM Grudziądz</name>
            <capacity>8000</capacity>
            <lighting>1800 lx</lighting>
            <length unit="m">379</length>
            <record>64.41</record>
        </stadion>

        <stadion id="SAS">
            <name>Stadion im. Alfreda Smoczyka</name>
            <capacity>16700</capacity>
            <lighting>1800 lx</lighting>
            <length unit="m">346</length>
            <record>58.53</record>
        </stadion>

        <stadion id="SMMB">
            <name>Stadion Miejski MOSiR "Bystrzyca"</name>
            <capacity>9800</capacity>
            <lighting>1800 lx</lighting>
            <length unit="m">382</length>
            <record>65.70</record>
        </stadion>

        <stadion id="MA">
            <name>MotoArena</name>
            <capacity>15500</capacity>
            <lighting>1800 lx</lighting>
            <length unit="m">318</length>
            <record>56.50</record>
        </stadion>

        <stadion id="NO">
            <name>Nowy Olimpijski</name>
            <capacity>13000</capacity>
            <lighting>1800 lx</lighting>
            <length unit="m">352</length>
            <record>60.99</record>
        </stadion>

        <stadion id="SKA">
            <name>Swiss Krono Arena</name>
            <capacity>14000</capacity>
            <lighting>1800 lx</lighting>
            <length unit="m">337</length>
            <record>58.22</record>
        </stadion>
    </stadions>

    <teams>
        <team id="FWC">
            <name>forBET Włókniarz Częstochowa</name>
            <address>
                <street>Olsztyńska 123</street>
                <housenumber>127</housenumber>
                <postcode>42-200</postcode>
                <city id="CZE">Częstochowa</city>
            </address>
            <email>klub@wlokniarz.com</email>
            <phonenumber>+48343619014</phonenumber>
            <establishmentyear>1946</establishmentyear>
            <president>Michał Świącik</president>
            <coach>Marek Cieślak</coach>
            <teamstadion refid="SGPAC"/>
            <win>3</win>
            <draw>0</draw>
            <lost>4</lost>
            <points>6</points>
            <bilans>-18</bilans>
        </team>

        <team id="TWSG">
            <name>TRULY.WORK Stal Gorzów</name>
            <address>
                <street>Kwiatowa  55</street>
                <housenumber/>
                <postcode>66-400</postcode>
                <city id="GW">Gorzów Wielkopolski</city>
            </address>
            <email>biuro@stalgorzow.pl</email>
            <phonenumber>+48957356245</phonenumber>
            <establishmentyear>1947</establishmentyear>
            <president>Ireneusz Zmora</president>
            <coach>Stanisław Chomski</coach>
            <teamstadion refid="SEJ"/>
            <win>3</win>
            <draw>0</draw>
            <lost>4</lost>
            <points>6</points>
            <bilans>-7</bilans>
        </team>

        <team id="GKM">
            <name>MRGARDEN GKM Grudziądz</name>
            <address>
                <street>Hallera 4</street>
                <housenumber/>
                <postcode>86-300</postcode>
                <city id="GDZ">Grudziądz</city>
            </address>
            <email>biuro@gkm.grudziadz.net</email>
            <phonenumber>+48564644442</phonenumber>
            <establishmentyear>1979</establishmentyear>
            <president>Marcin Murawski</president>
            <coach>Robert Kempiński</coach>
            <teamstadion refid="SGKMG"/>
            <win>2</win>
            <draw>1</draw>
            <lost>3</lost>
            <points>5</points>
            <bilans>-8</bilans>
        </team>

        <team id="FUL">
            <name>FOGO Unia Leszno</name>
            <address>
                <street>Strzelecka 7</street>
                <housenumber/>
                <postcode>64-100</postcode>
                <city id="LES">Leszno</city>
            </address>
            <email>klub@unia.leszno.pl</email>
            <phonenumber>+48655299977</phonenumber>
            <establishmentyear>1938</establishmentyear>
            <president>Piotr Rusiecki</president>
            <coach>Piotr Baron</coach>
            <teamstadion refid="SAS"/>
            <win>6</win>
            <draw>1</draw>
            <lost>0</lost>
            <points>13</points>
            <bilans>78</bilans>
        </team>

        <team id="SCML">
            <name>SPEED CAR MOTOR Lublin</name>
            <address>
                <street>Rusałka 6</street>
                <housenumber/>
                <postcode>20-103</postcode>
                <city id="LUB">Lublin</city>
            </address>
            <email>biuro@motorlublin.com.pl</email>
            <phonenumber>+48790550650</phonenumber>
            <establishmentyear>1962</establishmentyear>
            <president>Jakub Kępa</president>
            <coach>Jacek Ziółkowski</coach>
            <teamstadion refid="SMMB"/>
            <win>2</win>
            <draw>0</draw>
            <lost>5</lost>
            <points>4</points>
            <bilans>-40</bilans>
        </team>

        <team id="GWT">
            <name>Get Well Toruń</name>
            <address>
                <street>Pera Jonssona 7</street>
                <housenumber/>
                <postcode>87-100</postcode>
                <city id="TOR">Toruń</city>
            </address>
            <email>biuro@speedway.torun.pl</email>
            <phonenumber>+48566518066</phonenumber>
            <establishmentyear>1962 </establishmentyear>
            <president>Ilona Termińska</president>
            <coach>Jacek Frątczak</coach>
            <teamstadion refid="MA"/>
            <win>1</win>
            <draw>0</draw>
            <lost>5</lost>
            <points>2</points>
            <bilans>-49</bilans>
        </team>

        <team id="BSW">
            <name>BETARD SPARTA Wrocław</name>
            <address>
                <street>Paderewskiego 35</street>
                <housenumber/>
                <postcode>51-612</postcode>
                <city id="WRO">Wrocław</city>
            </address>
            <email>sekretariat@wts.pl</email>
            <phonenumber>+48717747925</phonenumber>
            <establishmentyear>1950</establishmentyear>
            <president>Andrzej Rusko</president>
            <coach>Dariusz Śledź</coach>
            <teamstadion refid="NO"/>
            <win>4</win>
            <draw>0</draw>
            <lost>3</lost>
            <points>8</points>
            <bilans>12</bilans>
        </team>

        <team id="SFZG">
            <name>STELMET FALUBAZ Zielona Góra</name>
            <address>
                <street>Wrocławska 69</street>
                <housenumber/>
                <postcode>65-218</postcode>
                <city id="ZG">Zielona Góra</city>
            </address>
            <email>sekretariat@zkzssa.pl</email>
            <phonenumber>+48684538911</phonenumber>
            <establishmentyear>1950</establishmentyear>
            <president>Adam Goliński</president>
            <coach>Adam Skórnicki</coach>
            <teamstadion refid="SKA"/>
            <win>5</win>
            <draw>0</draw>
            <lost>2</lost>
            <points>10</points>
            <bilans>32</bilans>
        </team>
    </teams>

    <riders>
        <rider>
            <firstname>Adrian</firstname>
            <lastname>Bialk</lastname>
            <birthdate>25-09-1999</birthdate>
            <nationality code="PL"/>
            <federation>PZM</federation>
            <riderteam refid="FWC"/>
        </rider>

        <rider>
            <firstname>Damian</firstname>
            <lastname>Dróżdż</lastname>
            <birthdate>20-12-1996</birthdate>
            <nationality code="PL"/>
            <federation>PZM</federation>
            <riderteam refid="FWC"/>
        </rider>

        <rider>
            <firstname>Michał</firstname>
            <lastname>Gruchalski</lastname>
            <birthdate>18-11-1998</birthdate>
            <nationality code="PL"/>
            <federation>PZM</federation>
            <riderteam refid="FWC"/>
        </rider>

        <rider>
            <firstname>Bartłomiej</firstname>
            <lastname>Kowalski</lastname>
            <birthdate>04-03-2002</birthdate>
            <nationality code="PL"/>
            <federation>PZM</federation>
            <riderteam refid="FWC"/>
        </rider>

        <rider>
            <firstname>Fredrik</firstname>
            <lastname>Lindgren</lastname>
            <birthdate>15-09-1985</birthdate>
            <nationality code="SE"/>
            <federation>SVEMO</federation>
            <riderteam refid="FWC"/>
        </rider>

        <rider>
            <firstname>Leon</firstname>
            <lastname>Madsen</lastname>
            <birthdate>05-09-1998</birthdate>
            <nationality code="DK"/>
            <federation>DMU</federation>
            <riderteam refid="FWC"/>
        </rider>

        <rider>
            <firstname>Adrian</firstname>
            <lastname>Miedziński</lastname>
            <birthdate>20-08-1985</birthdate>
